name: deploy_vue2

on: workflow_dispatch

env:
  REPOSITORY: "adnc"
  RUNNER_DEMO_SOURCE_ROOT: /home/runner/work/adnc-vue2/adnc-vue2
  NODE_ENV: production

jobs:
  build:

    runs-on: ubuntu-latest
       
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        
    - run: |
        npm i -g @vue/cli
        rm -rf node_modules package-lock.json && npm install    
    - run: |
        npm run build:prod
        
