name: deploy_vue2

on: workflow_dispatch

env:
  REPOSITORY: "adnc"
  RUNNER_DEMO_SOURCE_ROOT: /home/runner/work/adnc-vue2/adnc-vue2
  NODE_ENV: production

jobs:
  build:

    runs-on: ubuntu-latest
       
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Installing project dependencies     
    - run: npm install
    - name: Building the project
    - run: npm run build
        
