name: deploy_vue2

on: workflow_dispatch

env:
  REPOSITORY: "adnc"
  RUNNER_DEMO_SOURCE_ROOT: /home/runner/work/adnc-vue2/adnc-vue2
  NODE_ENV: production

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: |
        npm run build:prod
